name: PowerRanks
version: 2.0
main: nl.svenar.PowerRanks.PowerRanks
api-version: 1.13
authors: [svenar_nl]
load: startup
website: "https://svenar.nl/powerranks"
commands:
  powerranks:
    description: Main Command
  pr:
    description: Main Command